daemon:
    name: Client Agent #0

general:
    eventlogger: 127.0.0.1:7198
    dc_files:
        - ../dclass/empire.dc

uberdogs:

    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: TTEFriendsManager
      id: 4666
      anonymous: false

    - class: GlobalPartyManager
      id: 4477
      anonymous: false

    - class: TTFriendsManager
      id: 4697
messagedirector:
    connect: 127.0.0.1:7100

roles:
    - type: clientagent
      bind: 0.0.0.0:6667
      version: "empire-dev"
      client:
        relocate: true
        add_interest: enabled
      channels:
        min: 1000000000
        max: 1000001000
